// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aotkolrdhpgkwofritbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvdGtvbHJkaHBna3dvZnJpdGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjcyOTUsImV4cCI6MjA2NzA0MzI5NX0.wFuE0uOFB4p2VU2syUaxy6NR4je6aOIgewWtzXPgFQY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});